=== Jacobo-Dominguez/Jacobo-DAM/Acceso a datos/Pescaderia_JAXB/src/main/resources/Pescaderia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pescaderia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pescados"/>
        <xs:element ref="mariscos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pescados">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pescado" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pescado">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="tipo" type="xs:string"/>
        <xs:element name="temporada" type="xs:string"/>
        <xs:element name="procedencia" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mariscos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="marisco" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="marisco">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="temporada" type="xs:string"/>
        <xs:element name="procedencia" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jacobo-Dominguez/Jacobo-DAM/Acceso a datos/Pescaderia_JAXB/target/classes/Pescaderia.xml
<?xml version="1.0" encoding="UTF-8"?>
<pescaderia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Pescaderia.xsd">
<pescados>
  <pescado>
    <nombre>Merluza</nombre>
    <tipo>Pescado blanco</tipo>
    <temporada>Anual</temporada>
    <procedencia>Nacional</procedencia>
  </pescado>
  <pescado>
    <nombre>Salmon</nombre>
    <tipo>Pescado azul</tipo>
    <temporada>Anual</temporada>
    <procedencia>Importado</procedencia>
  </pescado>
  <pescado>
    <nombre>Bacalao</nombre>
    <tipo>Pescado blanco</tipo>
    <temporada>03,04,05,06</temporada>
    <procedencia>Atlántico Norte</procedencia>
  </pescado>
</pescados>
<mariscos>
  <marisco>
    <nombre> Mejillon</nombre>
    <temporada>09,10,11,12,01,02,03,04</temporada>
    <procedencia>Galicia</procedencia>
  </marisco>
  <marisco>
    <nombre>Gamba</nombre>
    <temporada>05,06,07,08</temporada>
    <procedencia>Atlantico</procedencia>
  </marisco>
  <marisco>
    <nombre>Cangrejo</nombre>
    <temporada>07,08,09</temporada>
    <procedencia>Cantabrico</procedencia>
  </marisco>
</mariscos>
</pescaderia>
